type = "checkout_ui_extension"
name = "perigeedirect-shippingapp-ext"
api_version = "2023-04" 

extension_points = [
  'Checkout::DeliveryAddress::RenderBefore',
  'Checkout::ShippingMethods::RenderBefore',
  'Checkout::Dynamic::Render'
]

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"

 [capabilities]
# network_access = true
 block_progress = true

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
# [settings]
#   [[settings.fields]]
#   key = "banner_title"
#   type = "single_line_text_field"
#   name = "Banner title"
#   description = "Enter a title for the banner"



